In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#read the data set 
dataset=pd.read_csv("Social_Network_Ads.csv")
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
#converting categorical data to numerical data
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [4]:
#Removing the unwanted cloumns from table
dataset=dataset.drop("User ID",axis=1)
dataset

Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [5]:
#input and output Split form data 
indep=dataset[["Age","EstimatedSalary","Gender_Male"]]
dep=dataset["Purchased"]

In [6]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [9]:
#model creation of Naive_bayes multinomiaLNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import GridSearchCV
param_grid = {'alpha':[1.0,2.0],'fit_prior':['True','False'], 'class_prior':[None]} 
grid = GridSearchCV( MultinomialNB(), param_grid,refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
# fitting the model for grid search 
grid.fit(X_train, y_train) 

Fitting 5 folds for each of 4 candidates, totalling 20 fits


GridSearchCV(estimator=MultinomialNB(), n_jobs=-1,
             param_grid={'alpha': [1.0, 2.0], 'class_prior': [None],
                         'fit_prior': ['True', 'False']},
             scoring='f1_weighted', verbose=3)

In [10]:
# print best parameter after tuning 
re=grid.cv_results_
grid_predictions = grid.predict(X_test) 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)
# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)
print('the confusion metrix is \n',cm)
print('the classification report is \n',clf_report)

the confusion metrix is 
 [[85  0]
 [49  0]]
the classification report is 
               precision    recall  f1-score   support

           0       0.63      1.00      0.78        85
           1       0.00      0.00      0.00        49

    accuracy                           0.63       134
   macro avg       0.32      0.50      0.39       134
weighted avg       0.40      0.63      0.49       134



C:\Anconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Anconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Anconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [11]:
#Calculate the F1Score 
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'alpha': 1.0, 'class_prior': None, 'fit_prior': 'True'}: 0.49240100865535336


In [12]:
#calculate the roc_auc_score 
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.5846338535414165

In [13]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_alpha  \
0       0.012967      0.006862         0.010955        0.005045         1.0   
1       0.003433      0.006866         0.013936        0.002293         1.0   
2       0.000000      0.000000         0.009195        0.007521         2.0   
3       0.001300      0.001933         0.001894        0.003787         2.0   

  param_class_prior param_fit_prior  \
0              None            True   
1              None           False   
2              None            True   
3              None           False   

                                              params  split0_test_score  \
0  {'alpha': 1.0, 'class_prior': None, 'fit_prior...           0.509779   
1  {'alpha': 1.0, 'class_prior': None, 'fit_prior...           0.509779   
2  {'alpha': 2.0, 'class_prior': None, 'fit_prior...           0.509779   
3  {'alpha': 2.0, 'class_prior': None, 'fit_prior...           0.509779   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.567088           0.590313           0.635834           0.557004   
1           0.567088           0.590313           0.635834           0.557004   
2           0.567088           0.590313           0.635834           0.557004   
3           0.567088           0.590313           0.635834           0.557004   

   mean_test_score  std_test_score  rank_test_score  
0         0.572004        0.041305                1  
1         0.572004        0.041305                1  
2         0.572004        0.041305                1  
3         0.572004        0.041305                1

In [14]:
Age_input=float(input("Age:"))
EstimatedSalary_input=float(input("EstimatedSalary:"))
Gender_input=float(input("Gender:"))

Age:55
EstimatedSalary:1000
Gender:1


In [15]:
Purchase_Prediction=grid.predict([[Age_input,EstimatedSalary_input,Gender_input]])
print("Purchase_Prediction={}".format(Purchase_Prediction))

Purchase_Prediction=[0]


C:\Anconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(


In [16]:
#model creation of Naive_bayes multinomiaLNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import GridSearchCV
param_grid = {'alpha':[1.0,2.0],'fit_prior':['True','False'], 'class_prior':[None]} 
grid = GridSearchCV( BernoulliNB(), param_grid,refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
# fitting the model for grid search 
grid.fit(X_train, y_train) 
# print best parameter after tuning 
re=grid.cv_results_
grid_predictions = grid.predict(X_test) 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)
# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)
print('the confusion metrix is \n',cm)
print('the classification report is \n',clf_report)

Fitting 5 folds for each of 4 candidates, totalling 20 fits
the confusion metrix is 
 [[85  0]
 [49  0]]
the classification report is 
               precision    recall  f1-score   support

           0       0.63      1.00      0.78        85
           1       0.00      0.00      0.00        49

    accuracy                           0.63       134
   macro avg       0.32      0.50      0.39       134
weighted avg       0.40      0.63      0.49       134



C:\Anconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Anconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Anconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [17]:
#Creation the model for naives bayes CategoricalNB
from sklearn.naive_bayes import CategoricalNB
from sklearn.model_selection import GridSearchCV
param_grid = {'alpha':[1.0,2.0],'fit_prior':['True','False'], 'class_prior':[None]} 
grid = GridSearchCV(CategoricalNB(), param_grid,refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
# fitting the model for grid search 
grid.fit(X_train, y_train) 
# print best parameter after tuning 
re=grid.cv_results_
grid_predictions = grid.predict(X_test) 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)
# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)
print('the confusion metrix is \n',cm)
print('the classification report is \n',clf_report)

Fitting 5 folds for each of 4 candidates, totalling 20 fits
the confusion metrix is 
 [[82  3]
 [18 31]]
the classification report is 
               precision    recall  f1-score   support

           0       0.82      0.96      0.89        85
           1       0.91      0.63      0.75        49

    accuracy                           0.84       134
   macro avg       0.87      0.80      0.82       134
weighted avg       0.85      0.84      0.84       134



C:\Anconda\lib\site-packages\sklearn\model_selection\_search.py:969: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan]
  warnings.warn(


In [18]:
#creation of model naies bayes complementNB
from sklearn.naive_bayes import ComplementNB
from sklearn.model_selection import GridSearchCV
param_grid = {'alpha':[1.0,2.0],'fit_prior':['True','False'], 'class_prior':[None]} 
grid = GridSearchCV(ComplementNB(), param_grid,refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
# fitting the model for grid search 
grid.fit(X_train, y_train) 
# print best parameter after tuning 
re=grid.cv_results_
grid_predictions = grid.predict(X_test) 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)
# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)
print('the confusion metrix is \n',cm)
print('the classification report is \n',clf_report)

Fitting 5 folds for each of 4 candidates, totalling 20 fits
the confusion metrix is 
 [[40 45]
 [20 29]]
the classification report is 
               precision    recall  f1-score   support

           0       0.67      0.47      0.55        85
           1       0.39      0.59      0.47        49

    accuracy                           0.51       134
   macro avg       0.53      0.53      0.51       134
weighted avg       0.57      0.51      0.52       134

